name: CI/CD for Controls

On:
  push:
    branches:
      - main

jobs:
  test:
  runs-on: ubuntu-latest

  steps:
    - name: Checkout code
      uses: actions/checout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with: python-version '3.11.6'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install RPi.GPIO

    - name: Run Tests
      run: Python LEDfade.py
