name: CI/CD for Controls
#Test
on:
  push:
    branches:
      - main

jobs:
  basic-ubuntu-20:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with: python-version '3.11.6'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install RPi.GPIO

      - name: Run Tests
        run: Python LEDfade.py
