name: CI/CD for Controls
#Test
on:
  push:
    branches:
      - main

jobs:
  basic-ubuntu-20:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with: python-version '3.9'

      - name: Install Dependencies
        run: pip install RPi.GPIO

      - name: Run Tests
        run: Python LEDfade.py
